name: Build client App and create deployable branch
on:
   push:
      branches:
         - main
jobs:
   prepare-build-cleanup-push:
      name: Prepare deploy branch, Build client application, Remove unneeded files, push to deploy branch
      runs-on: ubuntu-latest
      steps:
         - name: Checkout main branch
           uses: actions/checkout@main
         - name: Configure git
           run: |
              git config user.email ${{secrets.EMAIL}}
              git config user.name ${{secrets.NAME}}
         - name: Create deploy branch from master
           run: git branch deploy
         - name: Checkout deploy branch
           run: git checkout deploy
         - name: Remove previous client application build
           uses: JesseTG/rm@v1.0.2
           with:
              path: ./server/public
         - name: Install Dependencies for client application.
           working-directory: ./client
           run: npm install
         - name: Install Dependencies for server application.
           working-directory: ./server
           run: npm install
         - name: Build client application.
           working-directory: ./client
           run: CI=false npm run build
         - name: Remove .github folder
           uses: JesseTG/rm@v1.0.2
           with:
              path: ./.github
         - name: Remove client folder
           uses: JesseTG/rm@v1.0.2
           with:
              path: ./client
         - name: Remove .idea folder
           uses: JesseTG/rm@v1.0.2
           with:
              path: ./.idea
         - name: Remove .vscode folder
           uses: JesseTG/rm@v1.0.2
           with:
              path: ./.vscode
         - name: Remove .gitignore
           uses: JesseTG/rm@v1.0.2
           with:
              path: ./.gitignore
         - name: Remove README.md
           uses: JesseTG/rm@v1.0.2
           with:
              path: ./README.md
         - name: Push to deploy branch
           run: |
              git add -A .
              git commit -m "Deployable branch created by CI workflow."
              git push origin deploy -f
